-- 코드를 입력하세요
# SELECT CAR_TYPE, COUNT(*) AS CARS
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE OPTIONS IN ('통풍시트', '열선시트', '가죽시트')
# GROUP BY CAR_TYPE
# ORDER BY CAR_TYPE ASC

SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_cAR
WHERE (OPTIONS LIKE '%통풍시트%') | (OPTIONS LIKE '%열선시트%') | (OPTIONS LIKE '%가죽시트%')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC