-- 코드를 입력하세요
SELECT a.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS a
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
ON a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE = '세단' 
AND START_DATE LIKE '%-10-%'
GROUP BY a.CAR_ID 
ORDER BY a.CAR_ID DESC