-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',a.BOARD_ID, '/', b.FILE_ID, b.FILE_NAME, b.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS a
JOIN USED_GOODS_FILE AS b ON a.BOARD_ID = b.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY b.FILE_ID DESC
